x-shared-logs: &shared-logs
  logging:
    driver: "json-file"
    options:
      max-size: "10k"

services:
  api:
    restart: "unless-stopped"
    build:
      context: .
    ports:
      - "8000:8000"
    <<: *shared-logs
