x-shared-logs: &shared-logs
  logging:
    driver: "json-file"
    options:
      max-size: "10k"

x-shared-deploy: &shared-deploy
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [ gpu ]
  <<: *shared-logs

services:
  api:
    restart: "unless-stopped"
    build:
      context: .
    volumes:
      - ./models:/app/models
    ports:
      - "8000:8000"
    <<: *shared-deploy
